service: swift-lambda

provider:
  name: aws
  runtime: provided

package:
  artifact: .build/lambda/Lambda/lambda.zip

functions:
  lambda:
    handler: handler.lambda
    events:
      - http:
          path: /
          method: post
